alias: Turns off the light in the entry hallway after x minutes
hide_entity: true
trigger:
  - platform: state
    entity_id: 
      - light.hallway_entrance
    to: 'on'
    for: '00:01:00'
action:
  - service: light.turn_off
    data_template:
      entity_id: '{{ trigger.entity_id }}'
