alias: highHumiditySmallBathroom
trigger:
  platform: numeric_state
  entity_id: sensor.small_bathroom_humidity
  above: 70
action:
  - service: notify.telegram_notifier
    data_template:
      title: "Umiditate prea mare in baia mica !"
      message: "Ventilatorul ar trebui pornit."
  - service: tts.google_translate_say
    entity_id: "media_player.living_room_speaker"
    data:
      message: "There is high humidity in the small bathroom ! Please turn on the fan !"
    

