homeassistant:
  name: Home
  time_zone: Europe/Bucharest

discovery:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_named automation/
script: !include scripts.yaml
zone: !include zones.yaml

logger:
  default: info
  logs:
    homeassistant.components.zha: debug
    homeassistant.components.mqtt: debug
    bellows.ezsp: debug
    bellows.uart: debug
    zigpy.zdo: debug
    zigpy.application: debug

zha:
  usb_path: /dev/ttyAMA0
  database_path: /config/zigbee.db
  baudrate: 57600

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret ionut_telegram_chat_id

notify:
  - name: telegram_notifier
    platform: telegram
    chat_id: !secret ionut_telegram_chat_id

mqtt:
  broker: 192.168.1.36
  port: 1883
  username: mqtt
  password: !secret mqtt_pass
