views:
  - title: main
    icon: mdi:home-outline
    cards:
      - type: entities
        title: Zigbee
        entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.bridge_state
        show_header_toggle: false
      - type: light
        name: Living Room
        entity: group.living_room