alias: waterLeakKitchen
trigger:
  platform: state
  entity_id: binary_sensor.waterleak_kitchen_sink
  from: 'off'
  to: 'on'
action:
  - service: notify.telegram_notifier
    data_template:
      title: "Scurgere de apa la bucatarie !"
      message: "Verifica de ce este apa sub chiuveta."
  - service: tts.google_translate_say
    entity_id: "media_player.living_room_speaker"
    data:
      message: "There is water under the kitchen sink !"
    

