- platform: template 
  scan_interval: 5
  switches: 
    tv_panasonic_switch:
      friendly_name: 'TV Panasonic Switch'
      value_template: "{{ is_state('binary_sensor.panasonic_tv_status', 'on') }}"
      turn_on: 
        service: switch.turn_on
        entity_id: switch.tv_panasonic
      turn_off:
        service: switch.turn_off
        entity_id: switch.tv_panasonic
