- alias: normalHumiditySmallBathroom
  trigger:
    platform: numeric_state
    entity_id: <TODO>
    below: 60
  action:
    service: notify.telegram
    data_template:
      title: "Umiditatea in baia mica a ajuns la normal."
      message: "Ventilatorul a fost oprit deoarece umiditatea este {{ states.sensor.small_bathroom.humidity.state }} %"

